// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-aPFQsXpIxduZW1LxarGi2CTQijbb6r0',
    appId: '1:567940150908:web:fcd03c8c506ad4fb023bf9',
    messagingSenderId: '567940150908',
    projectId: 'migu-8983a',
    authDomain: 'migu-8983a.firebaseapp.com',
    storageBucket: 'migu-8983a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3tumLMiDRbsjf_b6-20tJWPf7h55rJ2U',
    appId: '1:567940150908:android:1d9cb64b31e8b524023bf9',
    messagingSenderId: '567940150908',
    projectId: 'migu-8983a',
    storageBucket: 'migu-8983a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWoZAn4ValA6sYY9EAyo5E3bI6BQoVC7k',
    appId: '1:567940150908:ios:f0fb3eed73d502b2023bf9',
    messagingSenderId: '567940150908',
    projectId: 'migu-8983a',
    storageBucket: 'migu-8983a.appspot.com',
    iosBundleId: 'com.example.migu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWoZAn4ValA6sYY9EAyo5E3bI6BQoVC7k',
    appId: '1:567940150908:ios:11b947bff1baa834023bf9',
    messagingSenderId: '567940150908',
    projectId: 'migu-8983a',
    storageBucket: 'migu-8983a.appspot.com',
    iosBundleId: 'com.example.migu.RunnerTests',
  );
}
